apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: vscode-debugging-python
build:
  artifacts:
    - image: vscode-debugging-python
deploy:
  # kubectl:
  #   manifests:
  #   - kubernetes/*.yaml
  helm:
    releases:
    - name: vscode-debugging-python
      chartPath: helm/vscode-debugging-python
      artifactOverrides:
        image.repository: vscode-debugging-python
      valuesFiles: [
        "helm/vscode-debugging-python/values.yaml",
        "skaffold_values.yaml"
      ]
