apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vscode-debugging-python.fullname" . }}
  labels:
    {{- include "vscode-debugging-python.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vscode-debugging-python.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vscode-debugging-python.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          #imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
