apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vscode-debugging-python.fullname" . }}
  labels:
    {{- include "vscode-debugging-python.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vscode-debugging-python.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vscode-debugging-python.selectorLabels" . | nindent 8 }}
    spec:
      {{- if eq .Values.skaffold "1" }}
      initContainers:
      - image: gcr.io/gcp-dev-tools/duct-tape/python
        imagePullPolicy: Always
        name: install-python-support
        volumeMounts:
        - mountPath: /dbg
          name: debugging-support-files
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      {{- if eq .Values.skaffold "1" }}
          args: [
            "/usr/local/bin/python",
            "-mptvsd",
            "--host",
            "0.0.0.0",
            "--port",
            "5678",
            "app.py"
          ]
          env:
            - name: PYTHONUSERBASE
              value: /dbg/python
          ports:
            - containerPort: 5678
              name: dap
              protocol: TCP
          volumeMounts:
            - mountPath: /dbg
              name: debugging-support-files
      volumes:
      - emptyDir: {}
        name: debugging-support-files
      {{- else }}
          command: ["/bin/bash"]
          args: ["-c", "python app.py"]
      {{- end }}
