apiVersion: v1
kind: Service
metadata:
  name: {{ include "vscode-debugging-python.fullname" . }}
  labels:
    {{- include "vscode-debugging-python.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "vscode-debugging-python.selectorLabels" . | nindent 4 }}
